apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: reddit-service-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: reddit
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
